export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";

export const CHECK_EMAIL = "CHECK_EMAIL";
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_ERROR = "CHECK_EMAIL_ERROR";

export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_ERROR = "VERIFY_EMAIL_ERROR";

export const CREATE_TIMESHEET = "CREATE_TIMESHEET";
export const CREATE_TIMESHEET_SUCCESS = "CREATE_TIMESHEET_SUCCESS";
export const CREATE_TIMESHEET_FAILURE = "CREATE_TIMESHEET_FAILURE";
export const CREATE_TIMESHEET_WORKINGHOUR = "CREATE_TIMESHEET_WORKINGHOUR";
export const CREATE_TIMESHEET_SAVE_WORKINGHOUR =
  "CREATE_TIMESHEET_SAVE_WORKINGHOUR";

export const EDIT_TIMESHEET = "EDIT_TIMESHEET";
export const EDIT_TIMESHEET_SUCCESS = "EDIT_TIMESHEET_SUCCESS";
export const EDIT_TIMESHEET_ERROR = "EDIT_TIMESHEET_ERROR";

export const UPDATE_TIMESHEET = "UPDATE_TIMESHEET";
export const UPDATE_TIMESHEET_SUCCESS = "UPDATE_TIMESHEET_SUCCESS";
export const UPDATE_TIMESHEET_ERROR = "UPDATE_TIMESHEET_ERROR";

export const DELETE_TIMESHEET = "DELETE_TIMESHEET";
export const DELETE_TIMESHEET_SUCCESS = "DELETE_TIMESHEET_SUCCESS";
export const DELETE_TIMESHEET_ERROR = "DELETE_TIMESHEET_ERROR";

export const TIMESHEET_LIST = "TIMESHEET_LIST";
export const TIMESHEET_LIST_SUCCESS = "TIMESHEET_LIST_SUCCESS";
export const TIMESHEET_LIST_ERROR = "TIMESHEET_LIST_ERROR";

export const EMP_TIMESHEET_LIST = "EMP_TIMESHEET_LIST";
export const EMP_TIMESHEET_LIST_SUCCESS = "EMP_TIMESHEET_LIST_SUCCESS";
export const EMP_TIMESHEET_LIST_ERROR = "EMP_TIMESHEET_LIST_ERROR";

export const APPROVE_TIMESHEET = "APPROVE_TIMESHEET";
export const APPROVE_TIMESHEET_SUCCESS = "APPROVE_TIMESHEET_SUCCESS";
export const APPROVE_TIMESHEET_ERROR = "APPROVE_TIMESHEET_ERROR";

export const TIMESHEET_STATUS = "TIMESHEET_STATUS";
export const TIMESHEET_STATUS_SUCCESS = "TIMESHEET_STATUS_SUCCESS";
export const TIMESHEET_STATUS_ERROR = "TIMESHEET_STATUS_ERROR";

export const FILEUPLOAD_TIMESHEET = "FILEUPLOAD_TIMESHEET";
export const FILEUPLOAD_TIMESHEET_SUCCESS = "FILEUPLOAD_TIMESHEET_SUCCESS";
export const FILEUPLOAD_TIMESHEET_ERROR = "FILEUPLOAD_TIMESHEET_ERROR";

export const LIST_EMPLOYEE_DETAILS = "LIST_EMPLOYEE_DETAILS";
export const LIST_EMPLOYEE_DETAILS_SERVER_RESPONSE_SUCESS =
  "LIST_EMPLOYEE_DETAILS_RESPONSE_SUCESS";
export const LIST_EMPLOYEE_DETAILS_SERVER__RESPONSE_ERROR =
  "LIST_EMPLOYEE_DETAILS_RESPONSE_ERROR";

export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_DETAILS_SERVER_RESPONSE_SUCESS =
  "CREATE_PROJECT_DETAILS_SERVER_RESPONSE_SUCESS";
export const CREATE_PROJECT_DETAILS_SERVER_RESPONSE_ERROR =
  "CREATE_PROJECT_DETAILS_SERVER_RESPONSE_ERROR";

export const CREATE_CLIENT = "CREATE_CLIENT";
export const CREATE_CLIENT_DETAILS_SERVER_RESPONSE_SUCCESS =
  "CREATE_CLIENT_DETAILS_SERVER_RESPONSE_SUCCESS";
export const CREATE_CLIENT_DETAILS_SERVER_RESPONSE_ERROR =
  "CREATE_CLIENT_DETAILS_SERVER_RESPONSE_ERROR";

export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_ERROR = "UPDATE_PROJECT_ERROR";

export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_ERROR = "UPDATE_CLIENT_ERROR";

export const ASSIGNED_PROJECT = "ASSIGNED_PROJECT";
export const ASSIGNED_PROJECT_SUCCESS = "ASSIGNED_PROJECT_SUCCESS";
export const ASSIGNED_PROJECT_ERROR = "ASSIGNED_PROJECT_ERROR";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_SUCESS = "DELETE_PROJECT_SUCESS";

export const DELETE_CLIENT = "DELETE_CLIENT";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";

export const EDIT_PROJECT_GET_DETAILS = "EDIT_PROJECT_GET_DETAILS";
export const EDIT_PROJECT_GET_DETAILS_SUCESS =
  "EDIT_PROJECT_GET_DETAILS_SUCESS";
export const EDIT_PROJECT_GET_DETAILS_ERROR = "EDIT_PROJECT_GET_DETAILS_ERROR";

export const LIST_PROJECT_DETAILS = "LIST_PROJECT_DETAILS";
export const LIST_PROJECT_DETAILS_SERVER_RESPONSE_SUCESS =
  "LIST_PROJECT_DETAILS_SERVER_RESPONSE_SUCESS";
export const LIST_PROJECT_DETAILS_SERVER_RESPONSE_ERROR =
  "LIST_PROJECT_DETAILS_SERVER_RESPONSE_ERROR";

export const LIST_CLIENT_DETAILS = "LIST_CLIENT_DETAILS";
export const LIST_CLIENT_DETAILS_SERVER_RESPONSE_SUCCESS =
  "LIST_CLIENT_DETAILS_SERVER_RESPONSE_SUCCESS";
export const LIST_CLIENT_DETAILS_SERVER_RESPONSE_ERROR =
  "LIST_CLIENT_DETAILS_SERVER_RESPONSE_ERROR";

export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SERVER_RESPONSE_ERROR =
  "SIGNUP_USER_SERVER_RESPONSE_ERROR";
export const SIGNUP_USER_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_USER_SERVER_RESPONSE_SUCCESS";

export const GET_USERS_LIST = "GET_USERS_LIST";
export const GET_USERS_LIST_SUCCESS_RESPONSE =
  "GET_USERS_LIST_SUCCESS_RESPONSE";
export const GET_USERS_LIST_ERROR_RESPONSE = "GET_USERS_LIST_ERROR_RESPONSE";

export const GET_USERS_LIST_SERVER_RESPONSE_SUCCESS =
  "GET_USERS_LIST_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_SAVE_DATABASE = "SIGNUP_SAVE_DATABASE";
export const SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_ERROR =
  "SIGNUP_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

export const EMPLOYEE_SAVE_DATABASE = "EMPLOYEE_SAVE_DATABASE";
export const EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS =
  "EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_ERROR =
  "EMPLOYEE_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const GET_EMPLOYEE_SELECTED_LIST = "GET_EMPLOYEE_SELECTED_LIST";
export const GET_EMPLOYEE_LIST_SUCCESS_RESPONSE =
  "GET_EMPLOYEE_LIST_SUCCESS_RESPONSE";
export const GET_EMPLOYEE_LIST_ERROR_RESPONSE =
  "GET_EMPLOYEE_LIST_ERROR_RESPONSE";

export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID";
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_ERROR = "EDIT_EMPLOYEE_ERROR";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";

export const GET_EMPLOYEE_BY_EMAIL = "GET_EMPLOYEE_BY_EMAIL";
export const GET_EMPLOYEE_BY_EMAIL_SUCCESS = "GET_EMPLOYEE_BY_EMAIL_SUCCESS";
export const GET_EMPLOYEE_BY_EMAIL_ERROR = "GET_EMPLOYEE_BY_EMAIL_ERROR";

export const SEARCH_EMP = "SEARCH_EMP";
export const SEARCH_EMP_SUCCESS = "SEARCH_EMP_SUCCESS";
export const SEARCH_EMP_ERROR = "SEARCH_EMP_ERROR";

export const PROJECT_LIST = "PROJECT_LIST";
export const PROJECT_LIST_SUCCESS_RESPONSE = "PROJECT_LIST_SUCCESS_RESPONSE";
export const PROJECT_LIST_ERROR_RESPONSE = "PROJECT_LIST_ERROR_RESPONSE";

export const CLIENT_SAVE_DATABASE = "CLIENT_SAVE_DATABASE";

export const VENDOR_SAVE_DATABASE = "VENDOR_SAVE_DATABASE";
export const VENDOR_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS =
  "VENDOR_SAVE_DATABASE_SERVER_RESPONSE_SUCCESS";
export const VENDOR_SAVE_DATABASE_SERVER_RESPONSE_ERROR =
  "VENDOR_SAVE_DATABASE_SERVER_RESPONSE_ERROR";

export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
export const UPDATE_VENDOR_ERROR = "UPDATE_VENDOR_ERROR";

export const LIST_VENDOR_DETAILS = "LIST_VENDOR_DETAILS";
export const LIST_VENDOR_DETAILS_SERVER_RESPONSE_SUCESS =
  "LIST_VENDOR_DETAILS_SERVER_RESPONSE_SUCESS";
export const LIST_VENDOR_DETAILS_SERVER_RESPONSE_ERROR =
  "LIST_VENDOR_DETAILS_SERVER_RESPONSE_ERROR";

export const DELETE_VENDOR = "DELETE_VENDOR";
export const DELETE_VENDOR_SUCESS = "DELETE_VENDOR_SUCESS";

export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
